// react/src/WafirReporter.tsx
import React, { useEffect, useRef } from "react";
import "wafir";

export type WafirPosition =
  | "bottom-right"
  | "bottom-left"
  | "top-right"
  | "top-left";

export interface WafirReporterProps {
  /** Installation ID for the wafir widget */
  installationId: number;
  /** GitHub repository owner */
  owner: string;
  /** GitHub repository name */
  repo: string;
  /** Widget button position */
  position?: WafirPosition;
  /** Modal title text */
  modalTitle?: string;
  /** Tooltip text for the trigger button */
  tooltipText?: string;
  /** Optional button text (shows instead of icon) */
  buttonText?: string;
}

interface WafirReporterElement extends HTMLElement {
  installationId?: number;
  owner?: string;
  repo?: string;
  position?: string;
  modalTitle?: string;
  tooltipText?: string;
  buttonText?: string;
}

/**
 * React wrapper component for the wafir-reporter web component.
 * Provides a type-safe interface for using the wafir feedback widget in React applications.
 */
export function WafirReporter({
  installationId,
  owner,
  repo,
  position = "bottom-right",
  modalTitle,
  tooltipText,
  buttonText,
}: WafirReporterProps) {
  const ref = useRef<WafirReporterElement>(null);

  // Set properties directly on the element when they change
  useEffect(() => {
    if (ref.current) {
      ref.current.installationId = installationId;
      ref.current.owner = owner;
      ref.current.repo = repo;
      if (position) ref.current.position = position;
      if (modalTitle) ref.current.modalTitle = modalTitle;
      if (tooltipText) ref.current.tooltipText = tooltipText;
      if (buttonText) ref.current.buttonText = buttonText;
    }
  }, [
    installationId,
    owner,
    repo,
    position,
    modalTitle,
    tooltipText,
    buttonText,
  ]);

  // Use createElement to avoid JSX typing issues with custom elements
  return React.createElement("wafir-reporter", { ref });
}

export default WafirReporter;

// packages/vue/src/WafirReporter.vue
<script setup lang="ts">
import { ref, watchEffect, onMounted } from "vue";
import "wafir";

export type WafirPosition =
  | "bottom-right"
  | "bottom-left"
  | "top-right"
  | "top-left";

export interface WafirReporterProps {
  installationId: number;
  owner: string;
  repo: string;
  position?: WafirPosition;
  modalTitle?: string;
  tooltipText?: string;
  buttonText?: string;
}

interface WafirReporterElement extends HTMLElement {
  installationId?: number;
  owner?: string;
  repo?: string;
  position?: string;
  modalTitle?: string;
  tooltipText?: string;
  buttonText?: string;
}

const props = withDefaults(defineProps<WafirReporterProps>(), {
  position: "bottom-right",
});

const elementRef = ref<WafirReporterElement | null>(null);

onMounted(() => {
  watchEffect(() => {
    if (elementRef.value) {
      elementRef.value.installationId = props.installationId;
      elementRef.value.owner = props.owner;
      elementRef.value.repo = props.repo;
      if (props.position) elementRef.value.position = props.position;
      if (props.modalTitle) elementRef.value.modalTitle = props.modalTitle;
      if (props.tooltipText) elementRef.value.tooltipText = props.tooltipText;
      if (props.buttonText) elementRef.value.buttonText = props.buttonText;
    }
  });
});
</script>

<template>
  <component :is="'wafir-reporter'" ref="elementRef">
    <template v-if="$slots.default">
      <div slot="trigger">
        <slot></slot>
      </div>
    </template>
  </component>
</template>
